export {
  applyDiff,
  bestFuzzyWindow,
  countNewlines,
  denied,
  err,
  levenshtein,
  linesTrimEqual,
  locateBlock,
  offsetOfLine,
  ok,
  parseDiffBlocks,
  previewNewFile,
  resultToString,
  similarity,
  unifiedDiff,
  type ApplyDiffResult,
  type BlockMatch,
  type DiffBlock,
  type ToolResult,
} from '@everyapi-ai/agent-core'
